## Numpy
- Numerical Python
- 파이썬의 고성능 과학 계산용 패키지
- Matrix와 Vector와 같은 Array 연산의 사실상 표준으로 사용된다

In [ ]:
# List에 비해 빠르고, 메모리 효율적
# 반복문 없이 데이터 배열에 대한 처리를 지원
# 선형대수와 관련된 다양한 기능을 제공
# C, C++, Portran 등의 언어와 통합 가능

In [2]:
import numpy as np # numpy 모듈 불러오기

In [5]:
# 중간에 문자열을 넣어도 numpy는 무조껀 하나의 data type만 가능해서 float형으로 바뀐다.
# List와 가장 큰 차이점, Dynamic typing not supported
test_array = np.array([1,4,"5",8], float) 
print(test_array)
type(test_array[2])

[1. 4. 5. 8.]


numpy.float64

In [4]:
test_array = np.array([1, 4, 5, "8"], float)
test_array

array([1., 4., 5., 8.])

In [5]:
print(type(test_array[3])) # float type

<class 'numpy.float64'>


In [6]:
print(test_array.dtype) # data type 확인

float64


In [10]:
print(test_array.shape) # shape 확인 (4,) 는 1차원이고 원소의 갯수가 4개짜리인 배열

(4,)


In [12]:
# array shape
vector = [1, 2, 3, 4]
print(np.array(vector, int).shape) # 1차원 원소가 4개라는것

(4,)


In [11]:
matrix = [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5,8]]
matrix = np.array(matrix, int).shape
print(np.array(matrix, int).shape) # 2차원 , 원소 갯수가 12개 라는 의미
print(type(matrix)) # type: tuple

(2,)
<class 'tuple'>


In [9]:
tensor = [[[1,2,5,8],[1,2,5,8],[1,2,5,8]],
          [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
          [[1,2,5,8],[1,2,5,8],[1,2,5,8]]]
tensor = np.array(tensor, int)
print(np.array(tensor, int).shape) # 3차원, 원소갯수 36 (3*3*4)
print(np.array(tensor, int).ndim) # 차원 알아보기
print(np.array(tensor, int).size) # 원소 갯수
print(type(tensor)) # ndarray 클래스는 다차원 행렬 자료 구조를 지원

(3, 3, 4)
3
36
<class 'numpy.ndarray'>


In [21]:
#numpy dtype
a = np.array([[1,2,3],[4.5,5,6]], dtype=int) # 자동으로 int 형 변환
print(a)

[[1 2 3]
 [4 5 6]]


In [22]:
np.array([[1, 2, 3], [4.5, "5", "6"]], dtype=np.float32)

array([[1. , 2. , 3. ],
       [4.5, 5. , 6. ]], dtype=float32)

In [23]:
np.array([[1, 2, 3], [4.5, "5", "6"]],
dtype=np.float32).nbytes

24

In [24]:
np.array([[1, 2, 3], [4.5, "5", "6"]],
dtype=np.int8).nbytes

6

In [25]:
np.array([[1, 2, 3], [4.5, "5", "6"]],
dtype=np.float64).nbytes

48

## 2_numpy_reshape
<br>
- Array의 Shape의 크기를 변경함 (element의 갯수는 동일)
- Array의 size만 같다면 다차원으로 자유로이 변형가능

In [12]:
test_matrix = [[1,2,3,4],[1,2,5,8]]

In [13]:
np.array(test_matrix).reshape(2,4).shape

(2, 4)

In [14]:
np.array(test_matrix).reshape(-1,2).shape # -1: size를 기반으로 row 개수 선정

(4, 2)

In [57]:
test_matrix = np.array(test_matrix).reshape(2,2,2) # 2차원 ->3차원으로 reshape 한다.
print(test_matrix)
print(test_matrix.shape)
print(test_matrix.ndim)

[[[1 2]
  [3 4]]

 [[1 2]
  [5 8]]]
(2, 2, 2)
3


In [58]:
test_matrix = np.array(test_matrix).reshape(8,)
print(test_matrix)
print(test_matrix.shape)
print(test_matrix.ndim)

[1 2 3 4 1 2 5 8]
(8,)
1


In [59]:
test_matrix = np.array(test_matrix).reshape(2,4)
print(test_matrix)
print(test_matrix.shape)
print(test_matrix.ndim)

[[1 2 3 4]
 [1 2 5 8]]
(2, 4)
2


In [60]:
test_matrix = np.array(test_matrix).reshape(2,4)
print(test_matrix)
print(test_matrix.shape)
print(test_matrix.ndim)

[[1 2 3 4]
 [1 2 5 8]]
(2, 4)
2


In [61]:
test_matrix = np.array(test_matrix).reshape(2,-1) # 앞 부분을 2행으로 만들고 -1의 의미는 뒤에 행부분을 고정시킨다는 의미
print(test_matrix)
print(test_matrix.shape)
print(test_matrix.ndim)

[[1 2 3 4]
 [1 2 5 8]]
(2, 4)
2


In [15]:
#flatten() ->다차원 array를 1차원 array로 변환
test_matrix = [[[1,2,3,4], [1,2,5,8]], [[1,2,3,4], [1,2,5,8]]]
test_matrix = np.array(test_matrix).flatten()
print(test_matrix)
print(test_matrix.shape)
print(test_matrix.ndim)

[1 2 3 4 1 2 5 8 1 2 3 4 1 2 5 8]
(16,)
1


## indexing
<br>
List와 달리 이차원 배열에서 [0,0] 과 같은 표기법을 제공
Matrix 일 경우 앞은 row 뒤는 column을 의미

In [16]:
# indexing
test_example = np.array([[1, 2, 3], [4.5, 5, 6]], int)
print(test_example)
print(test_example[0,0])
print(test_example[1][2])

[[1 2 3]
 [4 5 6]]
1
6


In [65]:
test_example[0][0]

1

In [66]:
test_example[0,0]

1

In [69]:
test_example[0,0] = 10
print(test_example)

[[10  2  3]
 [ 4  5  6]]


In [70]:
test_example[0][0] = 5
print(test_example)

[[5 2 3]
 [4 5 6]]


## Slicing
<br>

- List와 달리 행과 열 부분을 나눠서 slicing이 가능함

- Matrix의 부분 집합을 추출할 때 유용

In [2]:
from IPython.display import Image
Image("image.png")

In [72]:
test_example = np.array([[1, 2, 5, 8], [1, 2, 5, 8],[1, 2, 5, 8],[1, 2, 5, 8]], int)
test_example[:2,:] # ( :,2 : ) -> 행,렬 로 구분할 수 있는데 행 부분은 처음부터 첫번째 인덱스까지, 열은 다 가지고 오게 슬라이싱

array([[1, 2, 5, 8],
       [1, 2, 5, 8]])

In [17]:
print(test_example[:,1:3]) # 행,렬 (행은 전부다 슬라이싱, 열은 1~2까지 슬라이싱) 즉 4*4 -> 4*2
print()
print(test_example[1,:2])

[[2 3]
 [5 6]]

[4 5]


In [75]:
test_example = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], int)
test_example[:,2:] # Row 2

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [77]:
test_example[1,1:3] # 1 Row 1 ~ 2

array([7, 8])

In [78]:
test_example[1:3] # 1 Row ~ 2Row

array([[ 6,  7,  8,  9, 10]])

In [80]:
a = np.arange(100).reshape(10,10)
print(a)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [81]:
a[:, -1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [82]:
a[:, -1].reshape(2, 5)

array([[ 9, 19, 29, 39, 49],
       [59, 69, 79, 89, 99]])

## numpy_creation_function
<br>
- array의 범위를 지정하여, 값의 list를 생성하는 명령어

In [86]:
# arange
print(np.arange(30)) # range: List range , integer 0 29   range: List range , integer 0 29
print(np.arange(0, 5, 0.5)) # floating point
print(np.arange(30).reshape(5,6))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [87]:
#ones, zeros & empty
np.zeros(shape=(10,), dtype=np.int8) # 10 - zero vector  (shape, dtype, order)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [88]:
np.zeros((2,5)) # 2 by 5 - zero matrix

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [89]:
np.ones(shape=(10,), dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [90]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [91]:
np.empty(shape=(10,), dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [92]:
np.empty((3,5))

array([[2.12199579e-314, 6.36598737e-314, 1.06099790e-313,
        1.48539705e-313, 1.90979621e-313],
       [2.33419537e-313, 2.75859453e-313, 3.18299369e-313,
        3.60739285e-313, 4.03179200e-313],
       [4.45619116e-313, 4.88059032e-313, 5.30498948e-313,
        5.72938864e-313, 6.15378780e-313]])

In [4]:
import numpy as np
test_matrix = np.arange(30).reshape(5,6)
np.ones_like(test_matrix) # zero_like도 있고 등등... something_like

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [94]:
# eye, identity & digonal  
np.identity(n=3, dtype=np.int8) # 단위 행렬 (i)을 생성함

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [95]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [96]:
np.eye(N=3, M=5, dtype=np.int8) # 대각선이 1인 행렬, k값의 시작 index의 변경이 가능

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

In [97]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [98]:
np.eye(3,5,k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [99]:
matrix = np.arange(9).reshape(3,3)
np.diag(matrix) # 대각 행렬의 값을 추출함 (0, 4, 8)

array([0, 4, 8])

In [100]:
np.diag(matrix, k=1)

array([1, 5])

In [102]:
np.random.uniform(0,1,10).reshape(2,5) # 균등분포 생성

array([[0.66809685, 0.46413187, 0.03421927, 0.26417461, 0.54821511],
       [0.36985215, 0.94889128, 0.75537135, 0.76617641, 0.71081443]])

In [103]:
np.random.normal(0,1,10).reshape(2,5) # 정규분포 생성

array([[ 0.23061395, -0.5987097 , -0.75521328, -2.47625372,  0.64540124],
       [ 0.12690279, -0.13882774,  0.52211023,  0.30940917, -1.43774235]])

## ndarray_operation_functions

In [105]:
#operation in array
test_array = np.arange(1,11)
test_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [106]:
test_array.sum(dtype=np.float)

55.0

In [107]:
test_array = np.arange(1,13).reshape(3,4)
test_array.sum()

78

In [108]:
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# axis
# operation function을 실행할 때, 기준이 되는 dimension 축
# 2차원 ->(3,4) 가로, 세로 -> axis = 0, axis = 1
# 3차원 ->(3,3,4) depth,가로,세로 -> axis = 0, axis = 1, axis = 2

In [109]:
test_array.sum(axis=1), test_array.sum(axis=0)

(array([10, 26, 42]), array([15, 18, 21, 24]))

In [110]:
third_order_tensor = np.array([test_array,test_array,test_array])
third_order_tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [111]:
third_order_tensor.sum(axis=2)

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

In [112]:
third_order_tensor.sum(axis=1)

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

In [113]:
third_order_tensor.sum(axis=0)

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

In [114]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [115]:
test_array.mean(), test_array.mean(axis=0) # ndarray의 요소들 간의 평균 반환

(6.5, array([5., 6., 7., 8.]))

In [116]:
test_array.std(), test_array.std(axis=0) # ndarray의 요소들 간의 표준 편차

(3.452052529534663, array([3.26598632, 3.26598632, 3.26598632, 3.26598632]))

In [117]:
np.exp(test_array), np.sqrt(test_array)

(array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
        [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
        [8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05]]),
 array([[1.        , 1.41421356, 1.73205081, 2.        ],
        [2.23606798, 2.44948974, 2.64575131, 2.82842712],
        [3.        , 3.16227766, 3.31662479, 3.46410162]]))

In [118]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
np.vstack((a,b)) # 가로로 합치기 vertical

array([[1, 2, 3],
       [2, 3, 4]])

In [119]:
a = np.array([ [1], [2], [3]])
b = np.array([ [2], [3], [4]])
np.hstack((a,b)) # 세로로 합치기 horizontal

array([[1, 2],
       [2, 3],
       [3, 4]])

In [120]:
a = np.array([[1, 2, 3]])
b = np.array([[2, 3, 4]])
np.concatenate( (a,b) ,axis=0) # 기준을 정해서 array를 이어 붙임

array([[1, 2, 3],
       [2, 3, 4]])

In [122]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate( (a,b.T) ,axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [123]:
a.tolist() # 리스트로 변환

[[1, 2], [3, 4]]

## ndarray_operations
<br>
 - numpy는 array간의 기본적인 사칙연산을 지원

In [124]:
# Array operations
test_a = np.array([[1,2,3],[4,5,6]], float)
test_a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [125]:
test_a + test_a # Matrix + Matrix

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [126]:
test_a - test_a # Matrix - Matrix

array([[0., 0., 0.],
       [0., 0., 0.]])

In [128]:
test_a * test_a # Matrix element (element wise) 즉, 요소별 곱셈

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [129]:
matrix_a = np.arange(1,13).reshape(3,4)
matrix_a * matrix_a

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [130]:
# dot product 내적! -> 행렬곱셈
test_a = np.arange(1,7).reshape(2,3)
test_b = np.arange(7,13).reshape(3,2)

In [131]:
test_a

array([[1, 2, 3],
       [4, 5, 6]])

In [132]:
test_b

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [133]:
test_a.dot(test_b) # Matrix dot 행렬 곱

array([[ 58,  64],
       [139, 154]])

In [134]:
test_a = np.arange(1,7).reshape(2,3)
test_a

array([[1, 2, 3],
       [4, 5, 6]])

In [136]:
# transpose() or T
test_a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [137]:
test_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [138]:
test_a.T.dot(test_a) # Matrix

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

In [139]:
test_a.dot(test_a.T)

array([[14, 32],
       [32, 77]])

In [140]:
# broadcating ->원래는 곱셈이 안되는데 (계산되는 값이 확장되어 연산이 가능하다)
# shape이 다른 배열 간 연산을 지원하는 기능
# Scalar - Vector외에도 Vector-Matirx간의 연산도 지원
test_matrix = np.array([[1,2,3],[4,5,6]], float)
scalar = 3

In [141]:
test_matrix + scalar # Matrix - Scalar

array([[4., 5., 6.],
       [7., 8., 9.]])

In [142]:
test_matrix - scalar # Matrix - Scalar

array([[-2., -1.,  0.],
       [ 1.,  2.,  3.]])

In [143]:
test_matrix * 5 # Matrix - Scalar

array([[ 5., 10., 15.],
       [20., 25., 30.]])

In [144]:
test_matrix / 5 # Matrix - Scalar

array([[0.2, 0.4, 0.6],
       [0.8, 1. , 1.2]])

In [145]:
test_matrix // 0.2 # Matrix - Scalar

array([[ 4.,  9., 14.],
       [19., 24., 29.]])

In [146]:
test_matrix ** 2 # Matrix - Scalar

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [148]:
test_matrix = np.arange(1,13).reshape(4,3)
test_vector = np.arange(10,40,10)
print(test_matrix, test_vector)
test_matrix + test_vector

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] [10 20 30]


array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

In [152]:
# numpy performance
def sclar_vector_product(scalar, vector):
    result = []
    for value in vector:
        result.append(scalar * value)
    return result
iternation_max = 100000000
vector = list(range(iternation_max))
scalar = 2

%timeit sclar_vector_product(scalar, vector) # for loop
%timeit [scalar * value for value in range(iternation_max)] # list comprehension
%timeit np.arange(iternation_max) * scalar # numpy

12.2 s ± 173 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
11.3 s ± 64.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
461 ms ± 5.38 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


## numpy comparison


In [154]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [157]:
# Array의 데이터 전부(and) 또는 일부(or)가 조건에 만족 여부 반환
# 배열의 크기가 동일 할 때 element간 비교의 결과를 Boolean type으로 반환
b = a>5
print(b)

[False False False False False False  True  True  True  True]


In [156]:
a[b]

array([6, 7, 8, 9])

In [158]:
a < 0

array([False, False, False, False, False, False, False, False, False,
       False])

In [159]:
np.any(a>5), np.any(a<0)

(True, False)

In [160]:
np.all(a>5) , np.all(a < 10)

(False, True)

In [161]:
#comparision operation
test_a = np.array([1, 3, 0], float)
test_b = np.array([5, 2, 1], float)
test_a > test_b

array([False,  True, False])

In [162]:
test_a == test_b

array([False, False, False])

In [163]:
(test_a > test_b).any()

True

In [164]:
a = np.array([1, 3, 0], float)
np.logical_and(a > 0, a < 3) # and condition

array([ True, False, False])

In [165]:
b = np.array([True, False, True], bool)
np.logical_not(b) # NOT condition

array([False,  True, False])

In [166]:
c = np.array([False, True, False], bool)
np.logical_or(b, c) # OR condition

array([ True,  True,  True])

In [167]:
a

array([1., 3., 0.])

In [168]:
np.where(a > 0, 3, 2) # where(condition, TRUE, FALSE)

array([3, 3, 2])

In [169]:
a = np.arange(5, 15)
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [170]:
np.where(a>10)

(array([6, 7, 8, 9], dtype=int64),)

In [171]:
a = np.array([1, np.NaN, np.Inf], float)
np.isnan(a)

array([False,  True, False])

In [172]:
np.isfinite(a)

array([ True, False, False])

In [173]:
# argmax & argmin
# array내 최대값 또는 최소값의 index를 반환
a = np.array([1,2,4,5,8,78,23,3])
np.argmax(a) , np.argmin(a)

(5, 0)

In [174]:
# axis 기반의 반환도 가능하다.
a=np.array([[1,2,4,7],[9,88,6,45],[9,76,3,4]])
np.argmax(a, axis=1) , np.argmin(a, axis=0)

(array([3, 1, 1], dtype=int64), array([0, 0, 2, 2], dtype=int64))

## boolearn_fancy_index
<br>
- numpy는 array를 index value로 사용해서 값을 추출하는 방법 (matrix형태의 데이터도 가능)

In [175]:
#boolean index
test_array = np.array([1, 4, 0, 2, 3, 8, 9, 7], float)
test_array > 3

array([False,  True, False, False, False,  True,  True,  True])

In [176]:
test_array[test_array > 3]

array([4., 8., 9., 7.])

In [177]:
condition = test_array < 3
test_array[condition]

array([1., 0., 2.])

In [178]:
A = np.array([
[12, 13, 14, 12, 16, 14, 11, 10, 9],
[11, 14, 12, 15, 15, 16, 10, 12, 11],
[10, 12, 12, 15, 14, 16, 10, 12, 12],
[ 9, 11, 16, 15, 14, 16, 15, 12, 10],
[12, 11, 16, 14, 10, 12, 16, 12, 13],
[10, 15, 16, 14, 14, 14, 16, 15, 12],
[13, 17, 14, 10, 14, 11, 14, 15, 10],
[10, 16, 12, 14, 11, 12, 14, 18, 11],
[10, 19, 12, 14, 11, 12, 14, 18, 10],
[14, 22, 17, 19, 16, 17, 18, 17, 13],
[10, 16, 12, 14, 11, 12, 14, 18, 11],
[10, 16, 12, 14, 11, 12, 14, 18, 11],
[10, 19, 12, 14, 11, 12, 14, 18, 10],
[14, 22, 12, 14, 11, 12, 14, 17, 13],
[10, 16, 12, 14, 11, 12, 14, 18, 11]])
B = A < 15
B

array([[ True,  True,  True,  True, False,  True,  True,  True,  True],
       [ True,  True,  True, False, False, False,  True,  True,  True],
       [ True,  True,  True, False,  True, False,  True,  True,  True],
       [ True,  True, False, False,  True, False, False,  True,  True],
       [ True,  True, False,  True,  True,  True, False,  True,  True],
       [ True, False, False,  True,  True,  True, False, False,  True],
       [ True, False,  True,  True,  True,  True,  True, False,  True],
       [ True, False,  True,  True,  True,  True,  True, False,  True],
       [ True, False,  True,  True,  True,  True,  True, False,  True],
       [ True, False, False, False, False, False, False, False,  True],
       [ True, False,  True,  True,  True,  True,  True, False,  True],
       [ True, False,  True,  True,  True,  True,  True, False,  True],
       [ True, False,  True,  True,  True,  True,  True, False,  True],
       [ True, False,  True,  True,  True,  True,  True, False, 

In [179]:
B.astype(np.int)

array([[1, 1, 1, 1, 0, 1, 1, 1, 1],
       [1, 1, 1, 0, 0, 0, 1, 1, 1],
       [1, 1, 1, 0, 1, 0, 1, 1, 1],
       [1, 1, 0, 0, 1, 0, 0, 1, 1],
       [1, 1, 0, 1, 1, 1, 0, 1, 1],
       [1, 0, 0, 1, 1, 1, 0, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1]])

In [180]:
# fancy index
a = np.array([2, 4, 6, 8], float)

In [181]:
a[a>4]

array([6., 8.])

In [182]:
a.take(b) #take : bracket index

array([4., 2., 4.])

In [183]:
a = np.array([[1, 4], [9, 16]], float)
b = np.array([0, 0, 1, 1, 0], int)
c = np.array([0, 1, 1, 1, 1], int)
a[b,c] # b row index, c column index

array([ 1.,  4., 16., 16.,  4.])

In [184]:
a = np.array([[1, 4], [9, 16]], float)
a[b]

array([[ 1.,  4.],
       [ 1.,  4.],
       [ 9., 16.],
       [ 9., 16.],
       [ 1.,  4.]])